### ISSUE TITLE
Potential windows support

### ISSUE THREAD

**Issue by rsxdalv** [conda-forge/deepspeed-feedstock#19]
### Comment:

I found this reply for building a wheel - https://github.com/microsoft/DeepSpeed/issues/2427#issuecomment-1502628840

It's still far from a simple pipeline, but I was just curious to ask about the prospects of adding Windows to this conda package.

**Comment by weiji14** [comment]
The main issue is that the `conda-forge` channel does not have Pytorch on Windows (see https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32), so we can't build a `deepspeed` package for Windows here.

You might be able to try using the `pytorch` channel (which does have Windows builds) to install pytorch (e.g. https://anaconda.org/pytorch/pytorch/files?version=2.1.0) + any other required dependencies, and then try `pip install deepspeed`, but not sure if that would work (haven't got a Windows computer to test). Mixing `pytorch` from the `pytorch` channel and `deespeed` from `conda-forge channel would most likely not work though. Another alternative is to try something like Windows Subsystem for Linux.

**Comment by rsxdalv** [comment]
Thank you for the insight, sounds quite complicated to get this organized. Would you happen to know if the pytorch channel can be asked to add deepspeed? I couldn't find if they have a similar organization or repo on github to ask about this.

**Comment by weiji14** [comment]
Not sure if it's possible to add `deepspeed` to the [`pytorch` channel](https://anaconda.org/pytorch/repo) since it's a third-party package, but you could try asking on the Pytorch forum, e.g. the Windows category at https://discuss.pytorch.org/c/windows/26?

**Comment by loadams** [comment]
Hi @weiji14 - we are working on this on the DeepSpeed side, support will get here after that is added and released.

**Comment by rsxdalv** [comment]
> Hi @weiji14 - we are working on this on the DeepSpeed side, support will get here after that is added and released.

Thanks for the update! Is there an issue I can track to know when it's time to integrate it?

**Comment by loadams** [comment]
There are not any, there are a number of issues on the DeepSpeed side tracking this, but there will be an announcement when ready, and I'll update here as well.
