### ISSUE TITLE
Don't exclude all dso

### ISSUE THREAD

**Issue by hadim** [conda-forge/deepspeed-feedstock#4]
### Comment:

See https://github.com/conda-forge/staged-recipes/pull/21708#discussion_r1073497577 for context

**Comment by weiji14** [comment]
Not using `missing_dso_whitelist` anymore since https://github.com/conda-forge/deepspeed-feedstock/pull/66/commits/ba5c33dada6f465f9f9810bff84d60ef29211eb1 in #66, so closing.
